### ISSUE TITLE
Compilation failure during make

### ISSUE THREAD

**Issue by Reino17** [frabert/libdmusic#11]
Hello Francesco,

Cmake went fine, but with make I'm getting this:
```
[...]
Scanning dependencies of target dmusic
[ 27%] Building CXX object CMakeFiles/dmusic.dir/src/Articulator.cpp.obj
[ 28%] Building CXX object CMakeFiles/dmusic.dir/src/decode.cpp.obj
[ 30%] Building CXX object CMakeFiles/dmusic.dir/src/DlsPlayer.cpp.obj
In file included from /[...]/libdmusic_git/include/dmusic/InstrumentPlayer.h:4:0,
                 from /[...]/libdmusic_git/include/dmusic/DlsPlayer.h:11,
                 from /[...]/libdmusic_git/src/DlsPlayer.cpp:2:
/[...]/libdmusic_git/include/dmusic/Midi.h:37:28: warning: 'DirectMusic::Midi::Event::Type' is too small to hold all values of 'enum class DirectMusic::Midi::Message'
             Message Type : 4;
                            ^
In file included from /[...]/libdmusic_git/include/dmusic/DlsPlayer.h:12:0,
                 from /[...]/libdmusic_git/src/DlsPlayer.cpp:2:
/[...]/libdmusic_git/include/dmusic/PlayingContext.h:66:14: error: 'mutex' in namespace 'std' does not name a type
         std::mutex m_queueMutex;
              ^~~~~
make[2]: *** [CMakeFiles/dmusic.dir/build.make:114: CMakeFiles/dmusic.dir/src/DlsPlayer.cpp.obj] Error 1
make[1]: *** [CMakeFiles/Makefile2:68: CMakeFiles/dmusic.dir/all] Error 2
make: *** [Makefile:128: all] Error 2
```

**Comment by frabert** [comment]
Hi @Reino17, thanks for submitting this issue! May I ask you under what platform you are compiling, and what compiler version you're using? It would be very helpful, thanks 😄

**Comment by Reino17** [comment]
Windows. I'm using Cygwin, MingW64 and GCC.
Cmake log:
```
-- The C compiler identification is GNU 7.2.0
-- The CXX compiler identification is GNU 7.2.0
```

**Comment by frabert** [comment]
From what I was able to find on the net, it seems like MinGW has a somewhat flaky support for C++11 threads. I would try using a native mingw-w64 build (not a cygwin one) or, if that does not fix it, Clang or VC++>=2015, which is the "officially supported" method

**Comment by Reino17** [comment]
I'm sorry, but I'm not going to change my entire environment just for this.

I've noticed your reply to '_mzso_' [here](https://hydrogenaud.io/index.php/topic,103398.msg953626.html#msg953626) (my name's '_CoRoNe_' there). I've tried your binaries, but they seem to be x64, which I can't run.
I'll let this rest. Thanks anyway.

**Comment by frabert** [comment]
Sorry for the late reply, unfortunately I have been busy these days... Also I'm sorry this didn't work for you, to be honest I thought the automated builds would have been x86, I will try add both architectures, so maybe you will be able to check it out 😄 All the best!
