### ISSUE TITLE
Propose Logo

### ISSUE THREAD

**Issue by mirzazulfan** [frabert/libdmusic#14]
Hi @frabert ,, I'm graphic disigner. I would like to know if you are interested that I make a logo for your project? If you allowed me, i"ll make logo for your project and it's free.

**Comment by frabert** [comment]
I guess a new logo wouldn't hurt! Thanks for the offer! I'd like to keep it simple, tough, if possible :)

**Comment by mirzazulfan** [comment]
Hi @frabert , I've designed a logo for your project, tell me if you need something else. i'll make it for you. Thanks.
![libdmusic](https://user-images.githubusercontent.com/36124339/41048515-12f33e20-69d9-11e8-8f59-2efc99c51534.png)

**Comment by frabert** [comment]
Thank you, it's very nice :)
As I've never actually dealt with this kind of situations, I am not sure how to manage it, but I think the best way of doing it is I need you to sign this CLA to allow me to use your logo: https://www.clahub.com/agreements/frabert/libdmusic

This will - among other things - give me the copyright license for your work. I'll completely understand if you don't agree with this, but I won't be able to accept your contributions due to the MIT license this project is distributed with.

**Comment by mirzazulfan** [comment]
hi @frabert , i'm glad you liked it, it's free. Which one do you prefer ?
 
<a rel="license" href="http://creativecommons.org/licenses/by/4.0/"><img alt="Creative Commons License" style="border-width:0" src="https://i.creativecommons.org/l/by/4.0/88x31.png" /></a><br />This work is licensed under a <a rel="license" href="http://creativecommons.org/licenses/by/4.0/">Creative Commons Attribution 4.0 International License</a>.

**Comment by frabert** [comment]
I think I like the middle one the best :)

**Comment by mirzazulfan** [comment]
Tell me what kind size do you want ? I'll send you files and pr. Thanks @frabert

**Comment by frabert** [comment]
A vector file would be ideal, but I think a 1024px width image would be sufficient if not possible

**Comment by mirzazulfan** [comment]
Hi @frabert you can download all files (.SVG .PDF .PNG .PSD) here
[Drive](https://drive.google.com/drive/folders/1Mv17jVLK4q7JEwte5tyyzcutjLw-GEpc)
can you put the logo into readme file? that's enough for me. or may i create a pr ? thanks

**Comment by frabert** [comment]
I uploaded the logo on the [new-logo branch](https://github.com/frabert/libdmusic/tree/new-logo), I put credits to you on the bottom, in the "Acknowledgments" section

**Comment by mirzazulfan** [comment]
Thank you :+1:
