### ISSUE TITLE
dls2sf help?

### ISSUE THREAD

**Issue by LegoLoco7** [frabert/libdmusic#23]
What am I doing wrong here? Every time I get it to (presumably) load the file import, it doesn't export anything. I tried running cmd as administrator to see if that would change anything, but it didn't. This is the output from that second try:

>Microsoft Windows [Version 10.0.19045.2604]
>(c) Microsoft Corporation. All rights reserved.
>
>C:\Windows\system32>cd C:\Users\Win10_User\Documents\dmusic-0.1.5-win32\bin
>
>C:\Users\Win10_User\Documents\dmusic-0.1.5-win32\bin>dls2sf -i[C:\Program Files (x86)\LEGO Media\LEGO Island 2\_data\sounds\DirectMusic\z38PAR\Asteroids.dls] -o[Asteroids.sf2]
>Loading Files ...
>C:\Users\Win10_User\Documents\dmusic-0.1.5-win32\bin>dls2sf -i[Asteroids.dls] -o[Asteroids.sf2]
>dls2sf: no input specified.
>
>C:\Users\Win10_User\Documents\dmusic-0.1.5-win32\bin>dls2sf -i[C:\Users\Win10_User\Documents\dmusic-0.1.5-win32\bin\Asteroids.dls] -o[C:\Users\Win10_User\Documents\dmusic-0.1.5-win32\bin\Asteroids.sf2]
>dls2sf: no input specified.
>
>C:\Users\Win10_User\Documents\dmusic-0.1.5-win32\bin>

As you can see, on my final try, I copied the DLS file to the same folder as dls2sf, but that seemed to worsen the situation.

**Comment by frabert** [comment]
The help message is maybe a bit confusing, the paths should not be inside square brackets. Try this:

`dls2sf -i "C:\Program Files (x86)\LEGO Media\LEGO Island 2_data\sounds\DirectMusic\z38PAR\Asteroids.dls" -o "Asteroids.sf2"`

**Comment by LegoLoco7** [comment]
Okay, so it turns out there was a typo in the path with a missing backslash between LEGO Island 2 and _data, but even with your version of the command and that typo fix, dls2sf is still saying no input specified. I decided to try running cmd as administrator in the DLS file's folder, but it didn't help:

>C:\Program Files (x86)\LEGO Media\LEGO Island 2\_data\sounds\DirectMusic\z38PAR>C:\Users\Win10_User\Documents\dmusic-0.1.5-win32\bin\dls2sf.exe -i "C:\Program Files (x86)\LEGO Media\LEGO Island 2\_data\sounds\DirectMusic\z38PAR\Asteroids.dls" -o "Asteroids.sf2"
>dls2sf: no input specified.
>
>C:\Program Files (x86)\LEGO Media\LEGO Island 2\_data\sounds\DirectMusic\z38PAR>C:\Users\Win10_User\Documents\dmusic-0.1.5-win32\bin\dls2sf.exe -i "Asteroids.dls" -o "Asteroids.sf2"
>dls2sf: no input specified.

This was after restarting and updating Windows, not that it matters.

**Comment by LegoLoco7** [comment]
OH WAIT

**Comment by LegoLoco7** [comment]
Oh, false alarm, GitHub keeps removing a backslash due to formatting. I thought that was my problem for a second.

**Comment by LegoLoco7** [comment]
Perhaps it would be easier if I sent you the DLS file so you can convert it for me?

**Comment by frabert** [comment]
Sorry, haven't worked on this project for a long time and things are a bit fuzzy for me as well.

The `-i` flag is meant to specify a working directory, i.e. the place where additional files are to be searched. This is really only relevant when converting DirectMusic bands/styles, not DLS files.

The command you probably want is
```C:\Users\Win10_User\Documents\dmusic-0.1.5-win32\bin\dls2sf.exe -o "Asteroids.sf2" "Asteroids.dls"```

**Comment by LegoLoco7** [comment]
Tysm! That worked flawlessly after I ran cd C:\Users\Win10_User\Documents\dmusic-0.1.5-win32\bin.

**Comment by LegoLoco7** [comment]
Though, I might as well say that the output is very weird and echo-y, which is kind of a shame. It would be nice if I could fix this, but I probably can't.
